# Generated by Django 5.1.4 on 2024-12-11 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='name',
        ),
    ]
