# Generated by Django 5.1.4 on 2024-12-11 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_rename_my_user_user_alter_post_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='user_profile',
        ),
    ]
